=== Post 1.3.0 updates === * install_cbench_standalone - create a log file and parse it for any errors on install * opensource/ompi/Makefile - reference $(SRC) instead of openmpi * opensource/graph500/Makefile - quiet a sed statement * opensource/stress/Makefile - stress code is moving and author is rehosting, but use this git repository for now when compiling

diff --git a/cbench/install_cbench_standalone b/cbench/install_cbench_standalone
--- a/cbench/install_cbench_standalone
+++ b/cbench/install_cbench_standalone
@@ -18,6 +18,13 @@ export CBENCHSTANDALONEDIR
 
 sed -i -e "s#REPLACE_CBENCHSTANDALONEDIR#${CBENCHSTANDALONEDIR=}#" ${CBENCHOME}/cbench-standalonedir.sh 
 
-source ${CBENCHOME}/cbench-standalonedir.sh && make cbench_standalonedir_alldistclean && make cbench_standalone
+echo "Log file in $CBENCHOME/cbench_standalone_install.log"
+source ${CBENCHOME}/cbench-standalonedir.sh && make cbench_standalonedir_alldistclean > $CBENCHOME/cbench_standalone_install.log 2>&1 && make cbench_standalone >> $CBENCHOME/cbench_standalone_install.log 2>&1
+egrep -i 'error' $CBENCHOME/cbench_standalone_install.log
+if [ $? -eq 0 ]; then
+	echo "Errors found, examine: $CBENCHOME/cbench_standalone_install.log"
+else
+	echo "Installation is located in: $CBENCHSTANDALONEDIR"
+fi
 exit
 
