CDM: make perftest netfriendly

diff --git a/cbench/opensource/perftest/Makefile b/cbench/opensource/perftest/Makefile
--- a/cbench/opensource/perftest/Makefile
+++ b/cbench/opensource/perftest/Makefile
@@ -1,40 +1,54 @@
 include ../../make.def
 
-SUBDIR = ./perftest-1.3a
+VERSION=1.5
+SRC=perftest-$(VERSION)
+TAR=$(SRC).tar.gz
+URL="http://ftp.mcs.anl.gov/pub/mpi/tools/$(TAR)"
 
-EXECS = $(SUBDIR)/stress
-
+EXECS = src/stress
 INSTALLDIR = $(bin_dir)
 INSTALLTARGETS = $(EXECS)
-
-default: $(EXECS)
 
 # since the perftest configure snapshots the Cbench COMPILERCOLLECTION
 # and MPIHOME state, if the COMPILERCOLLECTION changes and perftest has
 # already been configured, we need to force a reconfigure
-ifeq ($(wildcard .config), .config)
-ifneq ($(shell cat .config), ${COMPILERCOLLECTION})
-	@echo "COMPILERCOLLECTION changed, forcing reconfigure.."
-	@/bin/rm -f .config $(SUBDIR)/Makefile $(EXECS)
-	$(MAKE)
-endif
-endif
+#ifeq ($(wildcard .config), .config)
+#ifneq ($(shell cat .config), ${COMPILERCOLLECTION})
+#	@echo "COMPILERCOLLECTION changed, forcing reconfigure.."
+#	@/bin/rm -f .config src/Makefile $(EXECS)
+#	$(MAKE)
+#endif
+#endif
 
-$(SUBDIR)/stress: $(SUBDIR)/Makefile $(SUBDIR)/stress.c
-	make -C $(SUBDIR) stress
+default: $(EXECS)
 
-$(SUBDIR)/Makefile:
-	echo ${COMPILERCOLLECTION} > .config
-	cd $(SUBDIR); export CC=$(CC); export F77=$(F77); \
-		export CFLAGS='$(CFLAGS)'; export FFLAGS='$(FFLAGS)'; \
-		./configure --with-mpich=
+$(TAR):
+	@echo "Downloading $(TAR)"
+	$(call download-url,$(URL))
+
+download: $(TAR)
+
+$(SRC): $(TAR)
+	@echo "Extracting $(SRC)"
+	@if [ -f $(TAR) ] ; then tar -zxf $(TAR); \
+	else \
+		echo "$(TAR) not found, download manually or set http_proxy env variable?"; \
+		exit 1; \
+	fi
+	ln -sf $(SRC) src
+
+configure: $(SRC)
+	echo ${COMPILERCOLLECTION} > src/.config
+	cd src; CC=$(PLAINCC) F77=$(PLAINF77) CFLAGS='$(CFLAGS)' FFLAGS='$(FFLAGS)' ./configure --with-mpi=$(MPIHOME)
+
+src/stress: configure
+	make -C src stress
 
 clean:
-	make -C $(SUBDIR) clean
+	$(MAKE) -C src clean
 
-distclean: clean
-	-make -C $(SUBDIR) distclean
-	/bin/rm -f .config
+distclean:
+	-/bin/rm -rf $(SRC) $(TAR) src .config
 
 install uninstall:
 	$(do-$@)
