CDM: update mdtest

diff --git a/cbench/opensource/mdtest/Makefile b/cbench/opensource/mdtest/Makefile
--- a/cbench/opensource/mdtest/Makefile
+++ b/cbench/opensource/mdtest/Makefile
@@ -1,8 +1,9 @@
 include ../../make.def
 
-SRC=mdtest-1.7.4
-TAR=$(SRC).tar.gz
-URL=http://downloads.sourceforge.net/project/mdtest/mdtest/$(SRC)/$(TAR)
+VERSION=1.8.3
+SRC=mdtest-$(VERSION)
+TAR=$(SRC).tgz
+URL="http://sourceforge.net/projects/mdtest/files/mdtest%20latest/$(SRC)/$(TAR)"
 
 EXECS = $(SRC)/mdtest
 INSTALLDIR = $(bin_dir)
@@ -11,21 +12,27 @@ INSTALLTARGETS = $(EXECS)
 all normal: $(EXECS)
 
 $(EXECS): $(SRC)
-	$(MAKE) CC.Linux=$(CC) -C $(SRC)
+	$(MAKE) CC=$(CC) -C $(SRC)
+
+$(TAR):
+	@echo "Downloading $(TAR)"
+	$(call download-sf-url,$(URL))
 
 $(SRC): $(TAR)
-	-[ ! -d $(SRC) ] && tar zxf $(TAR)
-	-[ ! -s src ] && ln -sf $(SRC) src
-
-$(TAR) download:
-	$(call download-url,$(URL))
-	-[ -e $(TAR) ] && touch $(TAR)
+	@echo "Extracting $(SRC)"
+	@if [ -f $(TAR) ] ; then tar -zxf $(TAR); \
+	else \
+		echo "$(TAR) not found, download manually or set http_proxy env variable?"; \
+		exit 1; \
+	fi
+	ln -sf $(SRC) src
 
 clean:
-	-[ -d $(SRC) ] && $(MAKE) -C $(SRC) clean || :
+	$(MAKE) -C src clean
 
 distclean:
 	/bin/rm -rf $(SRC) $(TAR) src
 
 install uninstall:
 	$(do-$@)
+
