CDM: make stress net friendly to get new versions

diff --git a/cbench/opensource/stress/Makefile b/cbench/opensource/stress/Makefile
--- a/cbench/opensource/stress/Makefile
+++ b/cbench/opensource/stress/Makefile
@@ -1,7 +1,10 @@
 include ../../make.def
 
-SRC=stress-0.18.9
+#SRC=stress-0.18.9
+VERSION=1.0.4
+SRC=stress-$(VERSION)
 TAR=$(SRC).tar.gz
+URL="http://weather.ou.edu/~apw/projects/stress/$(TAR)"
 
 EXEC = $(SRC)/src/stress
 INSTALLDIR = $(hwtest_bin_dir)
@@ -16,10 +19,19 @@ clean:
 	-$(MAKE) -C $(SRC) clean
 
 distclean:
-	-/bin/rm -rf $(SRC) .patched src
+	-/bin/rm -rf $(SRC) $(TAR) .patched src
+
+$(TAR):
+	@echo "Downloading $(TAR)"
+	$(call download-url,$(URL))
 
 $(SRC): $(TAR)
-	[ -d $(SRC) ] || tar zxf $(TAR) && rm -f .patched
+	@echo "Extracting $(SRC)"
+	@if [ -f $(TAR) ] ; then tar -zxf $(TAR); \
+	else \
+		echo "$(TAR) not found, download manually or set http_proxy env variable?"; \
+		exit 1; \
+	fi
 	ln -sf $(SRC) src
 
 .patched:
@@ -33,3 +45,5 @@ $(SRC): $(TAR)
 
 install uninstall:
 	$(do-$@)
+
+
