CDM: makefile fixes/standardization

diff --git a/cbench/opensource/conceptual/Makefile b/cbench/opensource/conceptual/Makefile
--- a/cbench/opensource/conceptual/Makefile
+++ b/cbench/opensource/conceptual/Makefile
@@ -1,21 +1,44 @@
 include ../../make.def
 
-VERSION=1.2
+VERSION=1.4
 SRC=conceptual-$(VERSION)
 TAR=$(SRC).tar.gz
 URL="http://sourceforge.net/projects/conceptual/files/conceptual/$(VERSION)/$(TAR)"
 
-$(SRC) build: download
-	-[ ! -d $(SRC) ] && tar zxf $(TAR)
-	cd $(SRC); MPICC=$(MPIHOME)/bin/mpicc ./configure --prefix=$(CBENCHTEST);
+default: .make-$(SRC)
 
-$(TAR) download:
-	$(call download-sf-url,$(URL),$(TAR))
-	-[ -e $(TAR) ] && touch $(TAR)
+download: $(TAR)
+
+$(TAR):
+	@echo "Downloading $(TAR)"
+	$(call download-sf-url,$(URL))
+
+$(SRC): $(TAR)
+	@echo "Extracting $(SRC)"
+	@if [ -f $(TAR) ] ; then tar -zxf $(TAR); \
+	else \
+		echo "$(TAR) not found, download manually or set http_proxy env variable?"; \
+		exit 1; \
+	fi
+	ln -sf $(SRC) src
+
+.configure-$(SRC): $(SRC)
+	@echo "Configuring $(SRC)"
+	cd src && MPICC=$(MPIHOME)/bin/mpicc ./configure --prefix=$(CBENCHTEST)/$(SRC) > ../.configure-$(SRC) 2>&1
+	@touch $@
+
+.make-$(SRC): .configure-$(SRC)
+	@echo "Compiling $(SRC)"
+	cd src && make > ../.make-$(SRC) 2>&1
+	@touch $@
 
 clean:
-	-[ -d $(SRC) ] && /bin/rm -fr $(SRC)
+	@if [ -f src/Makefile ] ; then $(MAKE) -C src clean; fi
+	rm -f .make-$(SRC) .configure-$(SRC)
 
-distclean: clean
-	-[ -f $(TAR) ] && /bin/rm -f $(TAR) 
+distclean:
+	rm -fr .make-$(SRC) .configure-$(SRC) src $(TAR) $(SRC)
 
+install: .make-$(SRC)
+	@echo "Installing $(SRC)"
+	cd src && make install >> ../.make-$(SRC) 2>&1
diff --git a/cbench/opensource/ctcs/Makefile b/cbench/opensource/ctcs/Makefile
--- a/cbench/opensource/ctcs/Makefile
+++ b/cbench/opensource/ctcs/Makefile
@@ -1,8 +1,8 @@
 include ../../make.def
 
 VERSION = 1.3.1pre1
-CTCS = ctcs-1.3.1-pre1
-TAR = $(CTCS).tgz
+SRC = ctcs-1.3.1-pre1
+TAR = $(SRC).tgz
 URL="http://sourceforge.net/projects/va-ctcs/files/va-ctcs/$(VERSION)/$(TAR)"
 
 INSTALLDIR = $(hwtest_bin_dir)
@@ -10,21 +10,35 @@ INSTALLTARGETS = src/runin/memtst
 
 default: all
 
-all:
-	$(MAKE) -C src CC=$(PLAINCC) CLINKER='$(PLAINCC) $(LDFLAGS)' CFLAGS='$(CFLAGS)' MEMTST_CFLAGS='$(CFLAGS) $(NOUNROLL_FLAGS)' $@
-
-distclean clean:
-	-[ -d $(CTCS) ] && rm -fr $(CTCS)
-	-[ -f $(TAR) ] && rm -f $(TAR)
-	$(MAKE) -C src dist-clean
-	-/bin/rm -rf src/runin/bin
-
-install uninstall:
-	$(do-$@)
+download: $(TAR)
 
 $(TAR):
 	@echo "Downloading $(TAR)"
 	$(call download-sf-url,$(URL),$(TAR))
-	-[ -e $(TAR) ] && touch $(TAR)
 
-download: $(TAR)
+$(SRC): $(TAR)
+	@echo "Extracting $(SRC)"
+	@if [ -f $(TAR) ] ; then tar -zxf $(TAR); \
+	else \
+		echo "$(TAR) not found, download manually or set http_proxy env variable?"; \
+		exit 1; \
+	fi
+	mv ctcs-1.3.1pre1 $(SRC)
+	ln -sf $(SRC) src
+
+all: $(SRC)
+	$(MAKE) -C src CC=$(PLAINCC) CLINKER='$(PLAINCC) $(LDFLAGS)' CFLAGS='$(CFLAGS)' MEMTST_CFLAGS='$(CFLAGS) $(NOUNROLL_FLAGS)' $@
+
+clean:
+	$(MAKE) -C src dist-clean
+	/bin/rm -rf src/runin/bin
+
+distclean:
+	rm -fr $(SRC) $(TAR) src
+
+
+install: default
+	$(do-$@)
+
+uninstall: 
+	$(do-$@)
